# Generated by Django 6.1.1 on 2026-09-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='video',
            name='cover_path',
            field=models.CharField(default='image/movies/m1.jpeg', max_length=255, verbose_name='مسیر کاور در استاتیک'),
        ),
    ]
